package main

import (
	//"crypto/sha256"
	"net/http"

	"database/sql"
	"log"
	"os"

	_ "github.com/lib/pq"
)

var (
	db *sql.DB
)

type bdInfo struct {
	id    int
	email string
	key   []byte
	salt  []byte
}

func connectDataBase() error {
	//connStr := "user=postgres password=37352410 dbname=postgres sslmode=disable"
	//db, err = sql.Open("postgres", connStr)

	var err error
	db, err = sql.Open("postgres", os.Getenv("DATABASE_URL"))
	if err != nil {
		return err
	}
	return nil
}

func disconnectDataBase() {
	db.Close()
}

func checkUser(logData logginDataClient) (*bdInfo, error) {
	var err error
	var infoClient *bdInfo

	err = connectDataBase()
	if err != nil {
		return nil, err
	}
	defer disconnectDataBase()

	rows, err := db.Query("SELECT id, email, key, salt FROM idusers WHERE email = $1", logData.Email)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	var id int
	var email string
	var key []byte
	var salt []byte

	for rows.Next() {
		if err = rows.Scan(&id, &email, &key, &salt); err != nil {
			return nil, err
		} else {
			infoClient = &bdInfo{id: id, email: email, key: key, salt: salt}
		}
	}

	return infoClient, err
}

func addUser(infoClient *bdInfo) error {
	var err error
	err = connectDataBase()
	if err != nil {
		return err
	}
	defer disconnectDataBase()

	//log.Println(infoClient)
	//
	// IDENTITY чекнуть!!!
	//
	if _, err := db.Exec("INSERT INTO idusers (email, key, salt) VALUES ($1, $2, $3)", infoClient.email, infoClient.key, infoClient.salt); err != nil {
		log.Println("test", err)
		return err
	}
	return err
}

func updateUser(infoClient *bdInfo) error {
	var err error
	err = connectDataBase()
	if err != nil {
		return err
	}
	defer disconnectDataBase()

	//
	// IDENTITY чекнуть!!!
	//

	_, err = db.Exec("UPDATE idusers SET key = $1, salt = $2 WHERE email = $3", infoClient.key, infoClient.salt, infoClient.email)
	if err != nil {
		return err
	}

	return err
}

func creatDB() {
	var err error
	err = connectDataBase()
	if err != nil {
		return
	}
	defer disconnectDataBase()

	if _, err := db.Exec("CREATE TABLE IF NOT EXISTS idusers (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, email text, key bytea, salt bytea)"); err != nil {
		return
	}
}

func infomydb(w http.ResponseWriter, r *http.Request) {
	var err error
	err = connectDataBase()
	if err != nil {
		return
	}
	defer disconnectDataBase()

	rows, err := db.Query("SELECT * FROM idusers")
	if err != nil {
		w.Write([]byte("Error reading idusers"))
		log.Println(err)
	}

	defer rows.Close()
	for rows.Next() {
		//var tick time.Time
		var id int
		var email string
		var key []byte
		var salt []byte

		if err := rows.Scan(&id, &email, &key, &salt); err != nil {
			w.Write([]byte("Error scanning ticks"))
			log.Println(err)
		}
		w.Write([]byte(string(id) + " -- " + email + " -- " + string(key) + " -- " + string(salt) + "\n"))
	}
}
